### PR TITLE
Add audio players for podcasts, other HTML render fixes

### LINKED ISSUE #261: Show podcast episodes and support audio playing

### PR DESCRIPTION
**Pull request by grace00**
## Reasons for making this change

- Certain HTML tags like iframe (for podcast audio) and strong weren't showing up in articles so I added custom renders/styles
- Removed descriptions because they take up a lot of space and tend to repeat the headline. I'll look into how we can reduce image space too.
- Added in subtitles for articles
- Fixed custom renders so Flourish charts appear

## Related tickets

fixes #261 #231 #263 

## Screenshots

Simulator Screen Shot - iPhone 8 Plus - 2020-05-19 at 01 16 18
Simulator Screen Shot - iPhone 8 Plus - 2020-05-19 at 01 20 04
Simulator Screen Shot - iPhone 8 Plus - 2020-05-19 at 01 15 53

### CODE REVIEW

File: app/HTML.js [hunk 1]
```diff
@@ -29,10 +30,17 @@ const renderers = {
         }}
       />);
     }
+    else if (htmlAttribs.class === "wp-block-embed__wrapper") {
+      let uri = children[0][0].props.source.uri;
```
Comment (epicfaace) [inline app/HTML.js:34]: Rather than doing this (it's not best practice to directly access children props if you can avoid it), could you try using something else like `passProps`?

File: app/HTML.js [hunk 2]
```diff
@@ -29,10 +30,17 @@ const renderers = {
         }}
       />);
     }
+    else if (htmlAttribs.class === "wp-block-embed__wrapper") {
```
Comment (epicfaace) [inline app/HTML.js:33]: When exactly does `wp-block-embed__wrapper` show up? Could you add a comment?

Comment (grace00) [reply app/HTML.js:33]: I added it for Spotify embeds, but I realized it also shows up for other things like Twitter embeds. I tried to make a custom render for iframes specifically to check the if the class has "Spotify" in it but I'm having trouble with making iframes show up.
