### PR TITLE
Changed article and header appearance, added fix for missing featured images

### LINKED ISSUE #232: Some featured images are missing
IMG_0797

### LINKED ISSUE #237: Reduce space between paragraphs

### PR DESCRIPTION
**Pull request by grace00**
## Reasons for making this change

- Articles: made aesthetic changes for readability
- Featured images: some featured images were missing before
- Header: I lost my previous changes through git somehow and added them back

## Related tickets

fixes #232 fixes #237 (mostly, a few articles still have abnormally large paragraph spacing and I'll look into it)

## Screenshots

Simulator Screen Shot - iPhone 8 Plus - 2020-05-16 at 19 38 34

### CODE REVIEW

File: app/screens/Post.js [hunk 1]
```diff
@@ -85,7 +85,7 @@ class Post extends Component {
       author: _.get(postData, "_embedded.author.name", ""),
       authorID: postData.author,
       date: new Date(postData.date).toLocaleDateString(),
-      featuredMedia: _.get(postData, "_embedded.wp:featuredmedia.0.media_details.sizes.medium_large.source_url"),
+      featuredMedia: _.get(postData, "_embedded.wp:featuredmedia.0.media_details.sizes.large.source_url"), // some articles are missing a medium_large image
```
Comment (epicfaace) [inline app/screens/Post.js:88]: ideally we should do the same fallback that's done in newsfeed-item.js (first try medium_large, then large, then full)
